version: '2.3'
services:
  cuda:
    build: 
      context: .
      dockerfile: Dockerfile_cuda
    container_name: Joint-NTF_cuda
    volumes:
      - ./:/Joint-NTF
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    ports:
      - "80:8888"
    command:
      jupyter-lab --ip 0.0.0.0  --allow-root -b localhost